Worked on by: Thomas Van Sande

In this notebook we'll build theforecasting model for the demand dataset using PyCaret.

# Predict

In [35]:
%pip uninstall dask -y
%pip uninstall distributed -y
%pip install "dask[dataframe]==2023.9.2" distributed==2023.9.2

Note: you may need to restart the kernel to use updated packages.

WARNING: Skipping dask as it is not installed.

Note: you may need to restart the kernel to use updated packages.

WARNING: Skipping distributed as it is not installed.

Collecting dask[dataframe]==2023.9.2
  Downloading dask-2023.9.2-py3-none-any.whl (1.2 MB)
     ---------------------------------------- 1.2/1.2 MB 7.6 MB/s eta 0:00:00
Collecting distributed==2023.9.2
  Downloading distributed-2023.9.2-py3-none-any.whl (994 kB)
     ------------------------------------- 994.9/994.9 kB 12.6 MB/s eta 0:00:00
Requirement already satisfied: importlib-metadata>=4.13.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from dask[dataframe]==2023.9.2) (6.8.0)
Requirement already satisfied: partd>=1.2.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from dask[dataframe]==2023.9.2) (1.4.2)
Requirement already satisfied: toolz>=0.10.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from dask[dataframe]==2023.9.2) (0.12.0)
Requirement already satisfied: click>=8.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from dask[dataframe]==2023.9.2) (8.1.4)
Requirement already satisfied: cloudpickle>=1.5.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from dask[dataframe]==2023.9.2) (3.1.2)
Requirement already satisfied: pyyaml>=5.3.1 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from dask[dataframe]==2023.9.2) (6.0.3)
Requirement already satisfied: fsspec>=2021.09.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from dask[dataframe]==2023.9.2) (2025.10.0)
Requirement already satisfied: packaging>=20.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from dask[dataframe]==2023.9.2) (25.0)
Requirement already satisfied: pandas>=1.3 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from dask[dataframe]==2023.9.2) (2.1.4)
Requirement already satisfied: tornado>=6.0.4 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from distributed==2023.9.2) (6.4.1)
Requirement already satisfied: tblib>=1.6.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from distributed==2023.9.2) (3.2.2)
Requirement already satisfied: zict>=3.0.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from distributed==2023.9.2) (3.0.0)
Requirement already satisfied: urllib3>=1.24.3 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from distributed==2023.9.2) (1.26.20)
Requirement already satisfied: msgpack>=1.0.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from distributed==2023.9.2) (1.1.2)
Requirement already satisfied: jinja2>=2.10.3 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from distributed==2023.9.2) (3.1.6)
Requirement already satisfied: locket>=1.0.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from distributed==2023.9.2) (1.0.0)
Requirement already satisfied: psutil>=5.7.2 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from distributed==2023.9.2) (5.9.5)
Requirement already satisfied: sortedcontainers>=2.0.5 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from distributed==2023.9.2) (2.4.0)
Requirement already satisfied: colorama in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from click>=8.0->dask[dataframe]==2023.9.2) (0.4.6)
Requirement already satisfied: zipp>=0.5 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from importlib-metadata>=4.13.0->dask[dataframe]==2023.9.2) (3.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from jinja2>=2.10.3->distributed==2023.9.2) (2.1.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pandas>=1.3->dask[dataframe]==2023.9.2) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pandas>=1.3->dask[dataframe]==2023.9.2) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pandas>=1.3->dask[dataframe]==2023.9.2) (2.8.2)
Requirement already satisfied: numpy<2,>=1.22.4 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pandas>=1.3->dask[dataframe]==2023.9.2) (1.26.4)
Requirement already satisfied: six>=1.5 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3->dask[dataframe]==2023.9.2) (1.16.0)
Installing collected packages: dask, distributed
Successfully installed dask-2023.9.2 distributed-2023.9.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [36]:
%pip install pandas matplotlib numpy
%pip install openpyxl
%pip install pycaret

Requirement already satisfied: pandas in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (2.1.4)
Requirement already satisfied: matplotlib in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (3.7.2)
Requirement already satisfied: numpy in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (1.26.4)
Requirement already satisfied: pytz>=2020.1 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (1.1.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: pillow>=6.2.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (9.5.0)
Requirement already satisfied: cycler>=0.10 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (4.40.0)
Requirement already satisfied: six>=1.5 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: openpyxl in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pycaret in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (3.3.2)
Requirement already satisfied: lightgbm>=3.0.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (4.6.0)
Requirement already satisfied: psutil>=5.9.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (5.9.5)
Requirement already satisfied: importlib-metadata>=4.12.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (6.8.0)
Requirement already satisfied: scipy<=1.11.4,>=1.6.1 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (1.11.4)
Requirement already satisfied: category-encoders>=2.4.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (2.7.0)
Requirement already satisfied: numpy<1.27,>=1.21 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (1.26.4)
Requirement already satisfied: ipywidgets>=7.6.5 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (8.1.8)
Requirement already satisfied: sktime==0.26.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (0.26.0)
Requirement already satisfied: statsmodels>=0.12.1 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (0.14.5)
Requirement already satisfied: schemdraw==0.15 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (0.15)
Requirement already satisfied: scikit-learn>1.4.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (1.4.2)
Requirement already satisfied: numba>=0.55.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (0.62.1)
Requirement already satisfied: nbformat>=4.2.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (5.10.4)
Requirement already satisfied: tqdm>=4.62.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (4.67.1)
Requirement already satisfied: plotly-resampler>=0.8.3.1 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (0.11.0)
Requirement already satisfied: joblib<1.4,>=1.2.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (1.3.2)
Requirement already satisfied: cloudpickle in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (3.1.2)
Requirement already satisfied: matplotlib<3.8.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (3.7.2)
Requirement already satisfied: plotly>=5.14.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (5.24.1)
Requirement already satisfied: pandas<2.2.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (2.1.4)
Requirement already satisfied: xxhash in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (3.6.0)
Requirement already satisfied: tbats>=1.1.3 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (1.1.3)
Requirement already satisfied: ipython>=5.5.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (8.29.0)
Requirement already satisfied: scikit-plot>=0.3.7 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (0.3.7)
Requirement already satisfied: markupsafe>=2.0.1 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (2.1.3)
Requirement already satisfied: pyod>=1.1.3 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (2.0.5)
Requirement already satisfied: yellowbrick>=1.4 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (1.5)
Requirement already satisfied: requests>=2.27.1 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (2.32.5)
Requirement already satisfied: jinja2>=3 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (3.1.6)
Requirement already satisfied: imbalanced-learn>=0.12.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (0.14.0)
Requirement already satisfied: pmdarima>=2.0.4 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (2.0.4)
Requirement already satisfied: deprecation>=2.1.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (2.1.0)
Requirement already satisfied: kaleido>=0.2.1 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pycaret) (1.2.0)
Requirement already satisfied: scikit-base<0.8.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from sktime==0.26.0->pycaret) (0.7.8)
Requirement already satisfied: packaging in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from sktime==0.26.0->pycaret) (25.0)
Requirement already satisfied: patsy>=0.5.1 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from category-encoders>=2.4.0->pycaret) (1.0.2)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from imbalanced-learn>=0.12.0->pycaret) (3.6.0)
Requirement already satisfied: zipp>=0.5 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from importlib-metadata>=4.12.0->pycaret) (3.16.0)
Requirement already satisfied: decorator in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from ipython>=5.5.0->pycaret) (5.1.1)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from ipython>=5.5.0->pycaret) (3.0.48)
Requirement already satisfied: typing-extensions>=4.6 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from ipython>=5.5.0->pycaret) (4.15.0)
Requirement already satisfied: matplotlib-inline in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from ipython>=5.5.0->pycaret) (0.1.7)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from ipython>=5.5.0->pycaret) (5.14.3)
Requirement already satisfied: stack-data in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from ipython>=5.5.0->pycaret) (0.6.3)
Requirement already satisfied: exceptiongroup in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from ipython>=5.5.0->pycaret) (1.3.1)
Requirement already satisfied: jedi>=0.16 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from ipython>=5.5.0->pycaret) (0.19.2)
Requirement already satisfied: pygments>=2.4.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from ipython>=5.5.0->pycaret) (2.15.1)
Requirement already satisfied: colorama in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from ipython>=5.5.0->pycaret) (0.4.6)
Requirement already satisfied: widgetsnbextension~=4.0.14 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets>=7.6.5->pycaret) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets>=7.6.5->pycaret) (3.0.16)
Requirement already satisfied: comm>=0.1.3 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets>=7.6.5->pycaret) (0.2.2)
Requirement already satisfied: pytest-timeout>=2.4.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from kaleido>=0.2.1->pycaret) (2.4.0)
Requirement already satisfied: logistro>=1.0.8 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from kaleido>=0.2.1->pycaret) (2.0.1)
Requirement already satisfied: choreographer>=1.1.1 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from kaleido>=0.2.1->pycaret) (1.2.1)
Requirement already satisfied: orjson>=3.10.15 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from kaleido>=0.2.1->pycaret) (3.11.4)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<3.8.0->pycaret) (1.1.0)
Requirement already satisfied: cycler>=0.10 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<3.8.0->pycaret) (0.11.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<3.8.0->pycaret) (2.8.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<3.8.0->pycaret) (4.40.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<3.8.0->pycaret) (3.0.9)
Requirement already satisfied: pillow>=6.2.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<3.8.0->pycaret) (9.5.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<3.8.0->pycaret) (1.4.4)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from nbformat>=4.2.0->pycaret) (5.7.2)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from nbformat>=4.2.0->pycaret) (2.20.0)
Requirement already satisfied: jsonschema>=2.6 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from nbformat>=4.2.0->pycaret) (4.18.0)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from numba>=0.55.0->pycaret) (0.45.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pandas<2.2.0->pycaret) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pandas<2.2.0->pycaret) (2023.3)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from plotly>=5.14.0->pycaret) (9.1.2)
Requirement already satisfied: tsdownsample>=0.1.3 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (0.1.4.1)
Requirement already satisfied: dash>=2.11.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (2.18.2)
Requirement already satisfied: setuptools!=50.0.0,>=38.6.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pmdarima>=2.0.4->pycaret) (80.9.0)
Requirement already satisfied: urllib3 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pmdarima>=2.0.4->pycaret) (1.26.20)
Requirement already satisfied: Cython!=0.29.18,!=0.29.31,>=0.29 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pmdarima>=2.0.4->pycaret) (3.2.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.27.1->pycaret) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.27.1->pycaret) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.27.1->pycaret) (2025.11.12)
Requirement already satisfied: simplejson>=3.19.3 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from choreographer>=1.1.1->kaleido>=0.2.1->pycaret) (3.20.2)
Requirement already satisfied: dash-table==5.0.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (5.0.0)
Requirement already satisfied: retrying in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.4.2)
Requirement already satisfied: nest-asyncio in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.6.0)
Requirement already satisfied: dash-core-components==2.0.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (2.0.0)
Requirement already satisfied: Flask<3.1,>=1.0.4 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (2.3.3)
Requirement already satisfied: dash-html-components==2.0.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (2.0.0)
Requirement already satisfied: Werkzeug<3.1 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (2.3.8)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from jedi>=0.16->ipython>=5.5.0->pycaret) (0.8.4)
Requirement already satisfied: attrs>=22.2.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (25.4.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.8.10)
Requirement already satisfied: referencing>=0.28.4 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.29.1)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (2023.6.1)
Requirement already satisfied: platformdirs>=2.5 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat>=4.2.0->pycaret) (3.8.1)
Requirement already satisfied: pywin32>=300 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat>=4.2.0->pycaret) (308)
Requirement already satisfied: wcwidth in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=5.5.0->pycaret) (0.2.6)
Requirement already satisfied: pytest>=7.0.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pytest-timeout>=2.4.0->kaleido>=0.2.1->pycaret) (7.4.4)
Requirement already satisfied: six>=1.5 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.7->matplotlib<3.8.0->pycaret) (1.16.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from stack-data->ipython>=5.5.0->pycaret) (2.4.1)
Requirement already satisfied: pure-eval in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from stack-data->ipython>=5.5.0->pycaret) (0.2.3)
Requirement already satisfied: executing>=1.2.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from stack-data->ipython>=5.5.0->pycaret) (2.1.0)
Requirement already satisfied: blinker>=1.6.2 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from Flask<3.1,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.9.0)
Requirement already satisfied: click>=8.1.3 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from Flask<3.1,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (8.1.4)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from Flask<3.1,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (2.2.0)
Requirement already satisfied: iniconfig in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido>=0.2.1->pycaret) (2.3.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido>=0.2.1->pycaret) (1.6.0)
Requirement already satisfied: tomli>=1.0.0 in c:\users\iljas\appdata\local\programs\python\python310\lib\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido>=0.2.1->pycaret) (2.0.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [37]:
import pickle
with open("cleaned_data.pkl", "rb") as file:
    df = pickle.load(file)

In [38]:
df.to_csv("cleaned_data.csv", index=False)

In [39]:
df.head()

,settlement_date,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,non_bm_stor,pump_storage_pumping,ifa_flow,britned_flow,moyle_flow
0,2006-01-01,1,38596,39660.0,34982,0.0,0.0,0.0,0.0,0,295,1997,0.0,-169.0
1,2006-01-01,2,38829,39897.0,35312,0.0,0.0,0.0,0.0,0,299,1997,0.0,-169.0
2,2006-01-01,3,38456,39599.0,35018,0.0,0.0,0.0,0.0,0,374,1998,0.0,-169.0
3,2006-01-01,4,37401,38823.0,34054,0.0,0.0,0.0,0.0,0,653,1998,0.0,-169.0
4,2006-01-01,5,36586,37937.0,33297,0.0,0.0,0.0,0.0,0,582,1998,0.0,-169.0

In [40]:
import pandas as pd
df['year'] = pd.DatetimeIndex(df['settlement_date']).year
df['month'] = pd.DatetimeIndex(df['settlement_date']).month
df['day'] = pd.DatetimeIndex(df['settlement_date']).day
df = df.drop(columns=['settlement_date'])

I want the granularity to be per month, since per day seems quite small for forecasting electricity demand

In [41]:
df_monthly = df.drop(columns=["day"]).groupby(["year","month"], as_index=False).mean()

In [42]:
df_monthly.head()

,year,month,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,non_bm_stor,pump_storage_pumping,ifa_flow,britned_flow,moyle_flow
0,2006,1,24.500000,44926.580645,46292.341398,40684.339382,0.0,0.0,0.0,0.0,2.492608,486.573925,1163.925403,0.0,-175.514785
1,2006,2,24.500000,45075.880208,46519.120536,40857.686756,0.0,0.0,0.0,0.0,2.793899,463.634673,597.453869,0.0,-93.101190
2,2006,3,24.469044,44233.642665,45466.306864,40027.205249,0.0,0.0,0.0,0.0,1.619112,467.188425,1425.873486,0.0,-124.381561
3,2006,4,24.500000,37960.129861,38886.315972,34293.731250,0.0,0.0,0.0,0.0,0.002083,272.236111,1901.654167,0.0,-153.297222
4,2006,5,24.500000,35744.225134,36721.996640,32444.974462,0.0,0.0,0.0,0.0,1.083333,347.650538,1739.044355,0.0,-124.606183

In [43]:
df_monthly.tail()

,year,month,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,non_bm_stor,pump_storage_pumping,ifa_flow,britned_flow,moyle_flow
233,2025,6,24.5,21847.457639,24444.728472,20143.653472,2002.455556,6606.0,3600.309028,20784.559028,0.0,129.782639,1004.897222,29.010417,-269.759722
234,2025,7,24.5,22665.625000,24896.304435,20755.875672,1188.024194,6606.0,3163.289651,20894.651882,0.0,93.918683,1539.971774,-43.504032,-175.690188
235,2025,8,24.5,21808.459005,24206.637769,19987.661290,1581.700269,6606.0,2909.141129,20396.096774,0.0,85.360215,1690.110215,48.041667,-277.826613
236,2025,9,24.5,23629.193750,26154.865278,21733.675694,2037.978472,6606.0,2292.840278,20993.000000,0.0,183.377778,1025.290278,-92.545833,-274.762500
237,2025,10,24.5,25664.076389,27957.263889,23998.680556,3111.798611,6606.0,947.750000,20993.000000,0.0,150.006944,516.368056,-257.326389,-85.472222

In [44]:
df_monthly = df_monthly.drop('settlement_period', axis=1)

In [45]:
df_monthly.head()

,year,month,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,non_bm_stor,pump_storage_pumping,ifa_flow,britned_flow,moyle_flow
0,2006,1,44926.580645,46292.341398,40684.339382,0.0,0.0,0.0,0.0,2.492608,486.573925,1163.925403,0.0,-175.514785
1,2006,2,45075.880208,46519.120536,40857.686756,0.0,0.0,0.0,0.0,2.793899,463.634673,597.453869,0.0,-93.101190
2,2006,3,44233.642665,45466.306864,40027.205249,0.0,0.0,0.0,0.0,1.619112,467.188425,1425.873486,0.0,-124.381561
3,2006,4,37960.129861,38886.315972,34293.731250,0.0,0.0,0.0,0.0,0.002083,272.236111,1901.654167,0.0,-153.297222
4,2006,5,35744.225134,36721.996640,32444.974462,0.0,0.0,0.0,0.0,1.083333,347.650538,1739.044355,0.0,-124.606183

Now we use PyCaret for building the model using the monthly granularity. We'll forecast the next 6 months

In [46]:
from pycaret.time_series import *
s = setup(
    data=df_monthly,
    target="england_wales_demand",
    fh=6,          
    session_id=123,
    fold=5
)

AttributeError: module 'dask.dataframe.core' has no attribute 'DataFrame'

In [ ]:
best = compare_models()
# Added by Iljas, saving a different way
final_best = finalize_model(best)
save_model(final_best, "different_save_best_model")

Auto arima provided the best model. Not surprising since auto arima is very good at dealing with seasonality and this dataset has very clear seasonality. We now save this model as a pickle file so we don't have to build this again and again when we want to use this. The evaluation metrics seem very good. An RMSE of 93 when dealing with numbers over 40k seems very accurate already. We'll also visualize this next.

In [ ]:
with open('best_model.pkl', 'wb') as file:
    pickle.dump(best, file)

In [ ]:
plot_model(best, plot = 'forecast', data_kwargs = {'fh' : 6})

As you can see, the model is very close to the actual data of the last 6 months

In [ ]:
import pickle

with open("best_model.pkl", "rb") as file:
    best = pickle.load(file)

In [ ]:
best.get_params()

{'D': None,
 'alpha': 0.05,
 'concentrate_scale': False,
 'd': None,
 'enforce_invertibility': True,
 'enforce_stationarity': True,
 'error_action': 'warn',
 'hamilton_representation': False,
 'information_criterion': 'aic',
 'max_D': 1,
 'max_P': 2,
 'max_Q': 2,
 'max_d': 2,
 'max_order': 5,
 'max_p': 5,
 'max_q': 5,
 'maxiter': 50,
 'measurement_error': False,
 'method': 'lbfgs',
 'mle_regression': True,
 'n_fits': 10,
 'n_jobs': 1,
 'offset_test_args': None,
 'out_of_sample_size': 0,
 'random': False,
 'random_state': 123,
 'scoring': 'mse',
 'scoring_args': None,
 'seasonal': True,
 'seasonal_test': 'ocsb',
 'seasonal_test_args': None,
 'simple_differencing': False,
 'sp': 12,
 'start_P': 1,
 'start_Q': 1,
 'start_p': 2,
 'start_params': None,
 'start_q': 2,
 'stationary': False,
 'stepwise': True,
 'suppress_warnings': True,
 'test': 'kpss',
 'time_varying_regression': False,
 'trace': False,
 'trend': None,
 'update_pdq': True,
 'with_intercept': True}

In [ ]:
best.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                     SARIMAX Results
==========================================================================================
Dep. Variable:                                  y   No. Observations:                  232
Model:             SARIMAX(2, 0, 0)x(2, 0, 0, 12)   Log Likelihood               -1336.737
Date:                            Mon, 24 Nov 2025   AIC                           2709.474
Time:                                    11:05:30   BIC                           2771.516
Sample:                                         0   HQIC                          2734.495
                                            - 232
Covariance Type:                              opg
=============================================================================================
                                coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------
year                          0.2928      0.092      3.199      0.001       0.113       0.472
month                        -6.7871      3.064     -2.215      0.027     -12.791      -0.783
nd                            0.8563      0.024     36.183      0.000       0.810       0.903
tsd                           0.0330      0.023      1.421      0.155      -0.012       0.078
embedded_wind_generation      0.1509      0.019      7.749      0.000       0.113       0.189
embedded_wind_capacity       -0.0639      0.023     -2.767      0.006      -0.109      -0.019
embedded_solar_generation    -0.1192      0.028     -4.258      0.000      -0.174      -0.064
embedded_solar_capacity       0.0271      0.008      3.432      0.001       0.012       0.043
non_bm_stor                   0.7338      1.263      0.581      0.561      -1.741       3.209
pump_storage_pumping          0.1214      0.155      0.784      0.433      -0.182       0.425
ifa_flow                     -0.0260      0.015     -1.709      0.087      -0.056       0.004
britned_flow                  0.0054      0.037      0.146      0.884      -0.066       0.077
moyle_flow                    0.0040      0.086      0.047      0.963      -0.164       0.172
ar.L1                         0.3381      0.069      4.899      0.000       0.203       0.473
ar.L2                         0.1984      0.070      2.829      0.005       0.061       0.336
ar.S.L12                      0.2658      0.076      3.478      0.001       0.116       0.416
ar.S.L24                      0.1564      0.080      1.955      0.051      -0.000       0.313
sigma2                     6551.6680    728.541      8.993      0.000    5123.753    7979.583
===================================================================================
Ljung-Box (L1) (Q):                   0.17   Jarque-Bera (JB):                 0.91
Prob(Q):                              0.68   Prob(JB):                         0.64
Heteroskedasticity (H):               1.82   Skew:                             0.15
Prob(H) (two-sided):                  0.01   Kurtosis:                         3.07
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).
"""