worked on by:

Building models

The previous part ended with a single notebook (per dataset) that would prepare your data for predicting. Next is building a couple of models and actually predicting something.

Which models will you need?

    A quick first model. This won't be a good one, but with this you can start working on the deployment (next step) while still tuning the model.
    Use PyCaret (or another automated ML comparison) on both datasets.
    Create and tune a model on both your datasets. Explain why you choose this particular model and perhaps train a second model to validate this choice.
    Create and tune a model on AWS.

Make sure to keep all the metrics on the models you made and compare these to show which model performed best.

# Predict

In [166]:
%pip install pandas matplotlib numpy
%pip install openpyxl
%pip install pycaret

Requirement already satisfied: pandas in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (2.1.4)
Requirement already satisfied: matplotlib in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (3.7.5)
Requirement already satisfied: numpy in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.1 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: six>=1.5 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: openpyxl in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pycaret in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (3.3.2)
Requirement already satisfied: ipython>=5.5.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (9.7.0)
Requirement already satisfied: ipywidgets>=7.6.5 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (8.1.8)
Requirement already satisfied: tqdm>=4.62.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (4.67.1)
Requirement already satisfied: numpy<1.27,>=1.21 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (1.26.4)
Requirement already satisfied: pandas<2.2.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (2.1.4)
Requirement already satisfied: jinja2>=3 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (3.1.6)
Requirement already satisfied: scipy<=1.11.4,>=1.6.1 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (1.11.4)
Requirement already satisfied: joblib<1.4,>=1.2.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (1.3.2)
Requirement already satisfied: scikit-learn>1.4.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (1.4.2)
Requirement already satisfied: pyod>=1.1.3 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (2.0.5)
Requirement already satisfied: imbalanced-learn>=0.12.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (0.14.0)
Requirement already satisfied: category-encoders>=2.4.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (2.7.0)
Requirement already satisfied: lightgbm>=3.0.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (4.6.0)
Requirement already satisfied: numba>=0.55.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (0.62.1)
Requirement already satisfied: requests>=2.27.1 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (2.32.5)
Requirement already satisfied: psutil>=5.9.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (7.1.3)
Requirement already satisfied: markupsafe>=2.0.1 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (3.0.3)
Requirement already satisfied: importlib-metadata>=4.12.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (8.7.0)
Requirement already satisfied: nbformat>=4.2.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (5.10.4)
Requirement already satisfied: cloudpickle in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (3.1.2)
Requirement already satisfied: deprecation>=2.1.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (2.1.0)
Requirement already satisfied: xxhash in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (3.6.0)
Requirement already satisfied: matplotlib<3.8.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (3.7.5)
Requirement already satisfied: scikit-plot>=0.3.7 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (0.3.7)
Requirement already satisfied: yellowbrick>=1.4 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (1.5)
Requirement already satisfied: plotly>=5.14.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (6.4.0)
Requirement already satisfied: kaleido>=0.2.1 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (1.2.0)
Requirement already satisfied: schemdraw==0.15 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (0.15)
Requirement already satisfied: plotly-resampler>=0.8.3.1 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (0.11.0)
Requirement already satisfied: statsmodels>=0.12.1 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (0.14.5)
Requirement already satisfied: sktime==0.26.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (0.26.0)
Requirement already satisfied: tbats>=1.1.3 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (1.1.3)
Requirement already satisfied: pmdarima>=2.0.4 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pycaret) (2.0.4)
Requirement already satisfied: packaging in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from sktime==0.26.0->pycaret) (25.0)
Requirement already satisfied: scikit-base<0.8.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from sktime==0.26.0->pycaret) (0.7.8)
Requirement already satisfied: patsy>=0.5.1 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from category-encoders>=2.4.0->pycaret) (1.0.2)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from imbalanced-learn>=0.12.0->pycaret) (3.6.0)
Requirement already satisfied: zipp>=3.20 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from importlib-metadata>=4.12.0->pycaret) (3.23.0)
Requirement already satisfied: colorama>=0.4.4 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from ipython>=5.5.0->pycaret) (0.4.6)
Requirement already satisfied: decorator>=4.3.2 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from ipython>=5.5.0->pycaret) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from ipython>=5.5.0->pycaret) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from ipython>=5.5.0->pycaret) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from ipython>=5.5.0->pycaret) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from ipython>=5.5.0->pycaret) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from ipython>=5.5.0->pycaret) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from ipython>=5.5.0->pycaret) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from ipython>=5.5.0->pycaret) (5.14.3)
Requirement already satisfied: typing_extensions>=4.6 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from ipython>=5.5.0->pycaret) (4.15.0)
Requirement already satisfied: comm>=0.1.3 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from ipywidgets>=7.6.5->pycaret) (0.2.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from ipywidgets>=7.6.5->pycaret) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from ipywidgets>=7.6.5->pycaret) (3.0.16)
Requirement already satisfied: choreographer>=1.1.1 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from kaleido>=0.2.1->pycaret) (1.2.1)
Requirement already satisfied: logistro>=1.0.8 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from kaleido>=0.2.1->pycaret) (2.0.1)
Requirement already satisfied: orjson>=3.10.15 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from kaleido>=0.2.1->pycaret) (3.11.4)
Requirement already satisfied: pytest-timeout>=2.4.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from kaleido>=0.2.1->pycaret) (2.4.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from matplotlib<3.8.0->pycaret) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from matplotlib<3.8.0->pycaret) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from matplotlib<3.8.0->pycaret) (4.60.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from matplotlib<3.8.0->pycaret) (1.4.9)
Requirement already satisfied: pillow>=6.2.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from matplotlib<3.8.0->pycaret) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from matplotlib<3.8.0->pycaret) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from matplotlib<3.8.0->pycaret) (2.9.0.post0)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from nbformat>=4.2.0->pycaret) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from nbformat>=4.2.0->pycaret) (4.25.1)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from nbformat>=4.2.0->pycaret) (5.9.1)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from numba>=0.55.0->pycaret) (0.45.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pandas<2.2.0->pycaret) (2025.2)
Requirement already satisfied: tzdata>=2022.1 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pandas<2.2.0->pycaret) (2025.2)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from plotly>=5.14.0->pycaret) (2.11.0)
Requirement already satisfied: dash>=2.11.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (3.3.0)
Requirement already satisfied: tsdownsample>=0.1.3 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (0.1.4.1)
Requirement already satisfied: Cython!=0.29.18,!=0.29.31,>=0.29 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pmdarima>=2.0.4->pycaret) (3.2.1)
Requirement already satisfied: urllib3 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pmdarima>=2.0.4->pycaret) (2.5.0)
Requirement already satisfied: setuptools!=50.0.0,>=38.6.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pmdarima>=2.0.4->pycaret) (65.5.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from requests>=2.27.1->pycaret) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from requests>=2.27.1->pycaret) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from requests>=2.27.1->pycaret) (2025.11.12)
Requirement already satisfied: simplejson>=3.19.3 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from choreographer>=1.1.1->kaleido>=0.2.1->pycaret) (3.20.2)
Requirement already satisfied: Flask<3.2,>=1.0.4 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (3.1.2)
Requirement already satisfied: Werkzeug<3.2 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (3.1.3)
Requirement already satisfied: retrying in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.4.2)
Requirement already satisfied: nest-asyncio in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from jedi>=0.18.1->ipython>=5.5.0->pycaret) (0.8.5)
Requirement already satisfied: attrs>=22.2.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.28.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat>=4.2.0->pycaret) (4.5.0)
Requirement already satisfied: wcwidth in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=5.5.0->pycaret) (0.2.14)
Requirement already satisfied: pytest>=7.0.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pytest-timeout>=2.4.0->kaleido>=0.2.1->pycaret) (9.0.1)
Requirement already satisfied: six>=1.5 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from python-dateutil>=2.7->matplotlib<3.8.0->pycaret) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from stack_data>=0.6.0->ipython>=5.5.0->pycaret) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from stack_data>=0.6.0->ipython>=5.5.0->pycaret) (3.0.0)
Requirement already satisfied: pure-eval in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from stack_data>=0.6.0->ipython>=5.5.0->pycaret) (0.2.3)
Requirement already satisfied: blinker>=1.9.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from Flask<3.2,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.9.0)
Requirement already satisfied: click>=8.1.3 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from Flask<3.2,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (8.3.0)
Requirement already satisfied: itsdangerous>=2.2.0 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from Flask<3.2,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (2.2.0)
Requirement already satisfied: iniconfig>=1.0.1 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido>=0.2.1->pycaret) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in c:\users\thoma\acs\machine learning\cloudai\project\null\venv_pycaret\lib\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido>=0.2.1->pycaret) (1.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [167]:
import pickle
with open("cleaned_data.pkl", "rb") as file:
    df = pickle.load(file)

In [168]:
df.head()

,settlement_date,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,non_bm_stor,pump_storage_pumping,ifa_flow,britned_flow,moyle_flow
0,2006-01-01,1,38596,39660.0,34982,0.0,0.0,0.0,0.0,0,295,1997,0.0,-169.0
1,2006-01-01,2,38829,39897.0,35312,0.0,0.0,0.0,0.0,0,299,1997,0.0,-169.0
2,2006-01-01,3,38456,39599.0,35018,0.0,0.0,0.0,0.0,0,374,1998,0.0,-169.0
3,2006-01-01,4,37401,38823.0,34054,0.0,0.0,0.0,0.0,0,653,1998,0.0,-169.0
4,2006-01-01,5,36586,37937.0,33297,0.0,0.0,0.0,0.0,0,582,1998,0.0,-169.0

In [169]:
import pandas as pd
df['year'] = pd.DatetimeIndex(df['settlement_date']).year
df['month'] = pd.DatetimeIndex(df['settlement_date']).month
df['day'] = pd.DatetimeIndex(df['settlement_date']).day
df = df.drop(columns=['settlement_date'])

In [170]:
df_monthly = df.drop(columns=["day"]).groupby(["year","month"], as_index=False).sum()

In [171]:
df_monthly.head()

,year,month,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,non_bm_stor,pump_storage_pumping,ifa_flow,britned_flow,moyle_flow
0,2006,1,36456,66850752,68883004.0,60538297,0.0,0.0,0.0,0.0,3709,724022,1731921,0.0,-261166.0
1,2006,2,32928,60581983,62521698.0,54912731,0.0,0.0,0.0,0.0,3755,623125,802978,0.0,-125128.0
2,2006,3,36361,65731193,67562932.0,59480427,0.0,0.0,0.0,0.0,2406,694242,2118848,0.0,-184831.0
3,2006,4,35280,54662587,55996295.0,49382973,0.0,0.0,0.0,0.0,3,392020,2738382,0.0,-220748.0
4,2006,5,36456,53187407,54642331.0,48278122,0.0,0.0,0.0,0.0,1612,517304,2587698,0.0,-185414.0

In [173]:
df_monthly.tail()

,year,month,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,non_bm_stor,pump_storage_pumping,ifa_flow,britned_flow,moyle_flow
233,2025,6,35280,31460339,35200409.0,29006861,2883536.0,9512640.0,5184445.0,29929765.0,0,186887,1447052,41775.0,-388454.0
234,2025,7,36456,33726450,37045701.0,30884743,1767780.0,9829728.0,4706975.0,31091242.0,0,139751,2291478,-64734.0,-261427.0
235,2025,8,36456,32450987,36019477.0,29741640,2353570.0,9829728.0,4328802.0,30349392.0,0,127016,2514884,71486.0,-413406.0
236,2025,9,35280,34026039,37663006.0,31296493,2934689.0,9512640.0,3301690.0,30229920.0,0,264064,1476418,-133266.0,-395658.0
237,2025,10,3528,3695627,4025846.0,3455810,448099.0,951264.0,136476.0,3022992.0,0,21601,74357,-37055.0,-12308.0

In [174]:
df_monthly = df_monthly.iloc[:-1]

In [175]:
df_monthly.tail()

,year,month,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,non_bm_stor,pump_storage_pumping,ifa_flow,britned_flow,moyle_flow
232,2025,5,36456,32299365,35623800.0,29436302,2247016.0,9829728.0,5339143.0,30532262.0,0,101952,1972434,28874.0,-542754.0
233,2025,6,35280,31460339,35200409.0,29006861,2883536.0,9512640.0,5184445.0,29929765.0,0,186887,1447052,41775.0,-388454.0
234,2025,7,36456,33726450,37045701.0,30884743,1767780.0,9829728.0,4706975.0,31091242.0,0,139751,2291478,-64734.0,-261427.0
235,2025,8,36456,32450987,36019477.0,29741640,2353570.0,9829728.0,4328802.0,30349392.0,0,127016,2514884,71486.0,-413406.0
236,2025,9,35280,34026039,37663006.0,31296493,2934689.0,9512640.0,3301690.0,30229920.0,0,264064,1476418,-133266.0,-395658.0

In [176]:
df_monthly = df_monthly.drop('settlement_period', axis=1)

In [177]:
df_monthly.head()

,year,month,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,non_bm_stor,pump_storage_pumping,ifa_flow,britned_flow,moyle_flow
0,2006,1,66850752,68883004.0,60538297,0.0,0.0,0.0,0.0,3709,724022,1731921,0.0,-261166.0
1,2006,2,60581983,62521698.0,54912731,0.0,0.0,0.0,0.0,3755,623125,802978,0.0,-125128.0
2,2006,3,65731193,67562932.0,59480427,0.0,0.0,0.0,0.0,2406,694242,2118848,0.0,-184831.0
3,2006,4,54662587,55996295.0,49382973,0.0,0.0,0.0,0.0,3,392020,2738382,0.0,-220748.0
4,2006,5,53187407,54642331.0,48278122,0.0,0.0,0.0,0.0,1612,517304,2587698,0.0,-185414.0

In [178]:
from pycaret.time_series import *
s = setup(
    data=df_monthly,
    target="england_wales_demand",
    fh=6,          
    session_id=123,
    fold=5
)

In [179]:
best = compare_models()

In [180]:
with open('best_model.pkl', 'wb') as file:
    pickle.dump(best, file)

In [181]:
plot_model(best, plot = 'forecast', data_kwargs = {'fh' : 6})